# Semgrep rules for Pirate Unified Wallet
# Security-focused static analysis

rules:
  # ========================================================================
  # Rust Security Rules
  # ========================================================================

  - id: rust-unsafe-usage
    patterns:
      - pattern: unsafe { ... }
    message: |
      Unsafe code detected. All crates should use #![forbid(unsafe_code)].
      Only exception: FFI boundary with careful review.
    severity: ERROR
    languages: [rust]
    paths:
      include:
        - "crates/**/*.rs"
      exclude:
        - "crates/pirate-ffi-frb/**/*.rs"  # Allow in FFI layer only

  - id: rust-unwrap-usage
    patterns:
      - pattern: $X.unwrap()
      - pattern: $X.expect(...)
    message: |
      Avoid unwrap()/expect() in production code. Use proper error handling with Result.
      Exception: test code and initialization where panic is acceptable.
    severity: WARNING
    languages: [rust]
    paths:
      include:
        - "crates/**/src/**/*.rs"
      exclude:
        - "crates/**/tests/**/*.rs"

  - id: rust-hardcoded-secret
    patterns:
      - pattern-either:
          - pattern: |
              let $VAR = "$SECRET";
          - pattern: |
              let $VAR: $TYPE = "$SECRET";
          - pattern: |
              const $VAR: $TYPE = "$SECRET";
      - metavariable-regex:
          metavariable: $SECRET
          regex: (password|secret|api_key|private_key|mnemonic)
      # Exclude test code
      - pattern-not-inside: |
          #[cfg(test)]
          mod tests {
            ...
          }
      - pattern-not-inside: |
          #[test]
          fn $FUNC(...) {
            ...
          }
      # Exclude test data variables
      - metavariable-pattern:
          metavariable: $VAR
          patterns:
            - pattern-not-regex: ^(test_|plaintext_|mock_|dummy_|fake_|example_).*
    message: |
      Potential hardcoded secret detected. Never commit secrets to source control.
      Note: Test data (in #[cfg(test)] modules or test_ prefixed variables) is excluded.
    severity: ERROR
    languages: [rust]
    paths:
      include:
        - "crates/**/src/**/*.rs"
      exclude:
        - "crates/**/tests/**/*.rs"

  - id: rust-sql-injection
    patterns:
      - pattern: |
          conn.execute(format!(...), ...)
      - pattern: |
          conn.query_row(format!(...), ...)
    message: |
      Potential SQL injection. Use parameterized queries with ? placeholders.
    severity: ERROR
    languages: [rust]

  - id: rust-panicking-in-production
    patterns:
      - pattern: panic!(...)
      - pattern: unimplemented!()
      - pattern: todo!()
    message: |
      Avoid panic!/unimplemented!/todo! in production code. Use proper error handling.
    severity: WARNING
    languages: [rust]
    paths:
      include:
        - "crates/**/src/**/*.rs"
      exclude:
        - "crates/**/tests/**/*.rs"

  - id: rust-println-in-production
    patterns:
      - pattern: println!(...)
      - pattern: dbg!(...)
    message: |
      Avoid println!/dbg! in production. Use tracing crate for structured logging.
    severity: WARNING
    languages: [rust]
    paths:
      include:
        - "crates/**/src/**/*.rs"

  - id: rust-weak-random
    patterns:
      - pattern: rand::thread_rng().gen()
    message: |
      Use cryptographically secure RNG for security-sensitive operations.
      Consider using OsRng or rand::rngs::StdRng with proper seeding.
    severity: WARNING
    languages: [rust]

  # ========================================================================
  # Dart/Flutter Security Rules
  # ========================================================================

  # Note: Dart Semgrep scans are DISABLED in CI due to persistent memory exhaustion
  # The rules below are retained for local development use only
  # The Rust layer handles all security-critical code (encryption, networking, key management)
  # Flutter/Dart layer is primarily UI - manual code review covers UI security concerns per .cursorrules
  
  - id: dart-print-usage
    patterns:
      - pattern: print(...)
    message: |
      Avoid print() in production. Use proper logging with log levels.
    severity: WARNING
    languages: [dart]
    paths:
      include:
        - "app/lib/**/*.dart"
      exclude:
        - "app/test/**/*.dart"
        - "app/lib/core/ffi/**/*.dart"  # Generated FFI code

  # ========================================================================
  # General Security Rules
  # ========================================================================

  - id: generic-todo-fixme
    patterns:
      - pattern-regex: (TODO|FIXME|HACK|XXX)
    message: |
      TODO/FIXME comment found. Ensure all TODOs are tracked in TODO.md before release.
    severity: INFO
    languages: [rust]  # Dart excluded to reduce memory usage

  # Note: generic-sensitive-data-log disabled for wallet codebase
  # These terms (mnemonic, seed, key) are legitimate domain language
  # and appear throughout the code in variable names, types, functions, etc.
  # Actual logging of secrets is prevented by:
  # 1. Code review process
  # 2. No println!/print() in production (caught by other rules)
  # 3. Structured logging with tracing crate (secrets not logged)
  
  - id: generic-actual-logging-of-secrets
    patterns:
      - pattern-either:
          - pattern: println!("... $SECRET ...")
          - pattern: tracing::info!("... $SECRET ...")
          - pattern: tracing::warn!("... $SECRET ...")
          - pattern: tracing::error!("... $SECRET ...")
      - metavariable-regex:
          metavariable: $SECRET
          regex: .*(mnemonic|seed_phrase|private_key|secret_key|passphrase).*
    message: |
      Actual logging of sensitive data detected. Never log mnemonics, seeds, or private keys.
    severity: ERROR
    languages: [rust]  # Dart excluded - secrets handled in Rust layer
    paths:
      include:
        - "crates/**/src/**"
      exclude:
        - "crates/**/tests/**"

  - id: generic-weak-crypto
    patterns:
      - pattern-regex: \b(MD5|SHA1|DES|RC4)\b
    message: |
      Weak cryptographic algorithm detected. Use modern algorithms (SHA256, AES-GCM, ChaCha20).
    severity: WARNING
    languages: [rust]  # Dart excluded - crypto handled in Rust layer
    paths:
      include:
        - "crates/**/src/**"
      exclude:
        - "crates/**/tests/**"

